# Generated by Django 3.1.7 on 2022-01-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('experience', models.CharField(max_length=200, verbose_name='Experience')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
                ('address', models.TextField(verbose_name='Address')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
                ('deadline', models.CharField(max_length=200, verbose_name='Deadline')),
                ('link', models.CharField(max_length=1000, null=True, verbose_name='Link')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Site Name')),
                ('link', models.URLField(verbose_name='Site Link')),
                ('tag', models.CharField(max_length=500, verbose_name='Selector Tag')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Qualification')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_sites.jobdata')),
            ],
        ),
        migrations.AddField(
            model_name='jobdata',
            name='job_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_sites.jobsite'),
        ),
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_link', models.URLField(max_length=1000, verbose_name='Sub Link')),
                ('tag', models.CharField(max_length=500, verbose_name='Selector Tag')),
                ('job_field', models.CharField(choices=[('name', 'name'), ('experience', 'experience'), ('description', 'description'), ('organization', 'organization'), ('address', 'address'), ('qualification', 'qualification'), ('attribute', 'attribute'), ('deadline', 'deadline')], max_length=50, verbose_name='Job Field')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_sites.jobsite')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Attribute')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_sites.jobdata')),
            ],
        ),
    ]
